# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Sangha1' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Sangha1
  pod 'AppCenter/Analytics', '~> 1.1.0'
  pod 'AppCenterReactNativeShared', '~> 1.1.0'
  pod 'AppCenter/Crashes', '~> 1.1.0'

  

  target 'Sangha1Tests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Sangha1-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Sangha1-tvOS

  target 'Sangha1-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
